version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: lc-store-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lc-store-db
    ports:
      - "3307:3306"
    volumes:
      - lc_store_db_data:/var/lib/mysql
    restart: always


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lc-store-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/lc-store-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    restart: always

volumes:
  lc_store_db_data:
